object frmTotalDebug: TfrmTotalDebug
  Left = 0
  Top = 0
  Caption = 'frmTotalDebug'
  ClientHeight = 417
  ClientWidth = 527
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = frmBaseCreate
  Right = 542
  Bottom = 455
  PixelsPerInch = 96
  TextHeight = 13
end
